// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    OSChart: typeof import('./src/components/OSChart.vue')['default']
    WaveGen: typeof import('./src/components/WaveGen.vue')['default']
    WaveGenChart: typeof import('./src/components/WaveGenChart.vue')['default']
  }
}
